version: '3'

services:
  mysql-db:
    image: mysql:5.7.10
    container_name: app-mysql-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: demo_nestjs
      MYSQL_ROOT_PASSWORD: P@ssword@123
      MYSQL_USER: thonguyen
      MYSQL_PASSWORD: admin
    networks:
      - mysql-internal
    volumes:
      - ./server/mysqldata:/var/lib/mysql

  mysql-gui:
    image: phpmyadmin:5.1.1-apache
    container_name: phpmyadmin-gui
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mysql-internal
    depends_on:
      - mysql-db

networks:
  mysql-internal:
    driver: bridge