@basic_url = http://127.0.0.1:3000/api

# Get all products
GET {{basic_url}}/products

###
# Get product by id
GET {{basic_url}}/products/10

###
# Create new product
POST {{basic_url}}/products/create
Content-Type: application/json

{
  "name": "iPhone 12 512GB",
  "quantity": 100,
  "price": 19000000,
  "description": "Hang nhap khau"
}

###
# Update product
# Route: /api/products/update/:id
PUT {{basic_url}}/products/update/1b3f987d-9313-4df2-b9a8-efe15eb561ec
Content-Type: application/json

{
  "name":"iPhone 12 Pro Max",
  "quantity":"16",
  "price":"12000000"
}

###
# Delete product
# route /api/produtcs/delete/:id
DELETE {{basic_url}}/products/delete/1b3f987d-9313-4df2-b9a8-efe15eb561ec

###
# Create new user (Register)
# Route: /api/user/register
POST {{basic_url}}/users/register
Content-Type: application/json

{
  "firstname":"Huu Tho",
  "lastname":"Nguyen",
  "address":"Ho Chi Minh City",
  "phone_number":"0934138065",
  "email":"huutho1999@gmail.com",
  "username":"tnguyen",
  "password":"123456"
}

###
# Login
POST {{basic_url}}/users/auth/login
Content-Type: application/json

{
  "username":"tnguyen77",
  "password":"huutho!0707"
}